//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcologySite.Localizations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("EcologySite.Localizations.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Anime_Link_Text {
            get {
                return ResourceManager.GetString("Anime_Link_Text", resourceCulture);
            }
        }
        
        public static string Home_AnimeGirlDesc {
            get {
                return ResourceManager.GetString("Home_AnimeGirlDesc", resourceCulture);
            }
        }
        
        public static string Home_Greatings {
            get {
                return ResourceManager.GetString("Home_Greatings", resourceCulture);
            }
        }
        
        public static string Home_Guest {
            get {
                return ResourceManager.GetString("Home_Guest", resourceCulture);
            }
        }
        
        public static string Home_HomePage {
            get {
                return ResourceManager.GetString("Home_HomePage", resourceCulture);
            }
        }
        
        public static string Home_Login {
            get {
                return ResourceManager.GetString("Home_Login", resourceCulture);
            }
        }
        
        public static string Home_Logout {
            get {
                return ResourceManager.GetString("Home_Logout", resourceCulture);
            }
        }
        
        public static string Home_Registration {
            get {
                return ResourceManager.GetString("Home_Registration", resourceCulture);
            }
        }
        
        public static string Home_Users {
            get {
                return ResourceManager.GetString("Home_Users", resourceCulture);
            }
        }
        
        public static string Home_Notification {
            get {
                return ResourceManager.GetString("Home_Notification", resourceCulture);
            }
        }
    }
}
